name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  sonarcloud:
    if: startsWith(github.head_ref, 'FE_') && github.event.pull_request.merged == false
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis relevance

     defaults:
        run:
        working-directory: ./myap

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
       defaults:
      run:
        working-directory: ./myap
      - name: Run Tests
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./myap # Specify the correct directory
          args: >
            -Dsonar.branch.name=${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  branchAnalysis:
    if: github.event.pull_request.merged == true
    name: Branch Analysis on PR merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis relevance

      - name: Change directory to myap
        run: cd myap # Change to the myap directory

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./myap # Specify the correct directory
          args: >
            -Dsonar.branch.name=main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
